name: Create DS4H-IA Release

on:
  workflow_run:
    workflows: ["Build the project using Maven"]
    types:
      - completed
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build JAR
        run: make create_release

      - name: Get Version Number
        id: version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: This is the release for version ${{ steps.version.outputs.version }} of Data Science For Health Image Alignment!
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/DS4H_ImageAlignment-${{ steps.version.outputs.version }}-all.jar
          asset_name: DS4H_ImageAlignment-${{ steps.version.outputs.version }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_SECRET }}
