name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Install Maven
        run: sudo apt-get install -y maven
      - name: Build JAR file
        run: make create_release
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}
          release_name: Release v${{ github.ref }}
          body: |
            Changes in this release:
            - Add new feature
            - Fix issue
          draft: false
          prerelease: false
      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: DS4H_ImageAlignment-${{ github.ref }}.jar
          path: target/my-project-${{ github.ref }}.jar
